// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO public.outbox (event_type, payload)
VALUES ($1, $2)
RETURNING id, event_type, payload, created_at
`

type InsertOutboxEventParams struct {
	EventType string
	Payload   []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent, arg.EventType, arg.Payload)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}
