// Code generated by avro/gen. DO NOT EDIT.
package events

// Event emitted when a new inventory item is created.
type InventoryItemCreated struct {
	ItemID    string `avro:"item_id" json:"item_id"`
	Name      string `avro:"name" json:"name"`
	Quantity  int32  `avro:"quantity" json:"quantity"`
	CreatedAt string `avro:"created_at" json:"created_at"`
}
